import { NextRequest, NextResponse } from "next/server"
import { z } from "zod"
import bcrypt from "bcrypt"
import { randomUUID } from "crypto"
import { prisma } from "@/lib/prisma"
import { redis, RedisKeys, TTL } from "@/lib/redis"
import { rateLimiters, checkRateLimit, getClientIp } from "@/lib/ratelimit"
import { sendVerificationEmail } from "@/lib/email"
import { logger, securityLogger } from "@/lib/logger"

const schema = z.object({
  username: z
    .string()
    .min(3)
    .max(30)
    .regex(/^[a-z0-9_]+$/, "Only lowercase letters, numbers and underscores"),
  password: z
    .string()
    .min(8)
    .regex(/(?=.*[a-zA-Z])(?=.*[0-9])/, "Must contain letter and number"),
  authMethod: z.enum(["EMAIL", "TELEGRAM"]),
  contact: z.string().min(1).max(255), // email or telegram username
})

export async function POST(req: NextRequest) {
  const ip = getClientIp(req)

  // Rate limit by IP
  const rl = await checkRateLimit(rateLimiters.signup, `ip:${ip}`)
  if (!rl.success) {
    return NextResponse.json(
      { error: "TOO_MANY_REQUESTS" },
      { status: 429, headers: { "Retry-After": String(rl.retryAfter) } }
    )
  }

  let body: unknown
  try {
    body = await req.json()
  } catch {
    return NextResponse.json({ error: "INVALID_JSON" }, { status: 400 })
  }

  const parsed = schema.safeParse(body)
  if (!parsed.success) {
    return NextResponse.json(
      { error: "VALIDATION_ERROR", details: parsed.error.flatten() },
      { status: 400 }
    )
  }

  const { username, password, authMethod, contact } = parsed.data

  // Check uniqueness
  const existing = await prisma.user.findFirst({
    where: {
      OR: [
        { username },
        authMethod === "EMAIL" ? { email: contact } : {},
      ],
    },
  })

  if (existing) {
    return NextResponse.json({ error: "USERNAME_TAKEN" }, { status: 409 })
  }

  const userId = randomUUID()
  const passwordHash = await bcrypt.hash(password, 10)

  const pendingData = {
    username,
    passwordHash,
    authMethod,
    ...(authMethod === "EMAIL" ? { email: contact } : { telegramUsername: contact }),
  }

  // Save pending registration to Redis
  await redis.set(RedisKeys.pendingReg(userId), JSON.stringify(pendingData), {
    ex: TTL.PENDING_REG,
  })

  // Fire-and-forget: send code
  if (authMethod === "EMAIL") {
    const code = String(Math.floor(1000 + Math.random() * 9000))
    // DEL old code first, then SET new one
    await redis.del(RedisKeys.code(userId))
    await redis.set(RedisKeys.code(userId), code, { ex: TTL.CODE })

    sendVerificationEmail(contact, code).catch((err) =>
      logger.error({ err, userId }, "Failed to send verification email")
    )

    logger.info({ userId, method: "EMAIL" }, "Signup initiated")
    return NextResponse.json({ pendingId: userId, expiresIn: TTL.PENDING_REG, method: "EMAIL" })
  } else {
    // Telegram: return deep link, code will be generated by bot
    const botUsername = process.env.TELEGRAM_BOT_USERNAME
    const deepLink = `https://t.me/${botUsername}?start=reg_${userId}`

    logger.info({ userId, method: "TELEGRAM" }, "Signup initiated")
    return NextResponse.json({
      pendingId: userId,
      expiresIn: TTL.PENDING_REG,
      method: "DEEPLINK",
      deepLink,
    })
  }
}
